### ISSUE TITLE
Project doesn't install anything

### ISSUE THREAD

**Issue by yurivict** [brummer10/FatFrog.lv2#3]

**Comment by brummer10** [comment]
works here as expected. 
You may give a bit more information to find out why it didn't work for you.
For example, when you try to build a distribution package you may involve the `INSTALL_DIR` make flag to overwrite the default.
Also the DESTDIR env variable is respected by the makefile.

**Comment by yurivict** [comment]
It is incompatible with package build as it is.
```
        ifeq ($(user),root)
        INSTALL_DIR ?= /usr/lib/lv2
        else
        INSTALL_DIR ?= ~/.lv2
        endif
```

1. Package builders now work as user, not as ```root```, so normally project is expected to be installed into ```$DESTDIR$PREFIX```.
2. ```/usr``` should be ```$PREFIX```.

**Comment by brummer10** [comment]
@yurivict 
with lv2 plugins we've a game changer, as those could be easily installed on ~./lv2 as user.  Means users could just build and install as a user and expect  it to work.
So, as packager you may overwrite the  `INSTALL_DIR` parameter which could be done in your build script.

**Comment by yurivict** [comment]
Ok, thanks.
